name = "auth-uid"
main = "src/index.js"
compatibility_date = "2025-11-15"

[build.upload]
format = "modules"   # ‚Üê WAJIB untuk import lokal dari node_modules

[[d1_databases]]
binding = "DB"
database_name = "sssaham"
database_id = "7d5a7db1-3845-49df-8a37-17b44e35e186"

[vars]
JWT_SECRET = "GANTI_SECRET_RANDOM"
OTP_PROVIDER_URL = "https://example.com/send-otp"
OTP_API_KEY = "SECRET_OTP_KEY"
